### ISSUE TITLE
Issue with android gradle plugin version 3.3 and OneSignal

### ISSUE THREAD

**Issue by SuyashBDA** [OneSignal/OneSignal-Gradle-Plugin#84] opened 2019-02-10 09:10 UTC
When I updated, `Gradle 4.6 -> 4.10.1` and the `Android Gradle plugin 3.2.1 -> 3.3.1`, I get the following errors:

>ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0).
Show Details
Affected Modules: app

>ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.android.support:support-v4:[26.0.0, 27.2.0).
Show Details
Affected Modules: app

>ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.android.support:customtabs:[26.0.0, 27.2.0).
Show Details
Affected Modules: app

>ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-location:[10.2.1, 12.1.0).
Show Details
Affected Modules: app

>ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[10.2.1, 12.1.0).
Show Details
Affected Modules: app

While inspecting dependancies I found OneSignal `implementation 'com.onesignal:OneSignal:3.10.6'` was throwing above errors for ex.

```sh
> Could not resolve com.google.android.gms:play-services-location:[15.0.0, 16.0.0).
     Required by:
         project :app > com.onesignal:OneSignal:3.10.6
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/ec-android-sdk/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/ec-android-sdk/com/google/android/gms/play-services-location/maven-metadata.xml'.
```

Now coming to `https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/ec-android-sdk` is used to fetch the dependencies required for [JustPay integration](https://juspay.in/docs/advanced/ec/android_integration/index.html).

**Problem**
Why wrong repository is used when resolving above dependancies for compiling the project? 

*Solution* : Excluding this libs does solves the problem.

```sh
implementation ('com.onesignal:OneSignal:3.10.6') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'customtabs'
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
        exclude group: 'com.google.firebase', module: 'firebase-messaging'
}
```

I am not sure, It may have adverse affects though(If any please do let me know). I know it has something to do with **Improved classpath synchronization** but I can't get to the root of the problem, can you please help me?

Here is my app/build.gradle file

```sh
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath "io.fabric.tools:gradle:$rootProject.fabricGradle"
    }

    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }

    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.1'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'
apply plugin: 'project-report'

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
    maven { url 'https://maven.fabric.io/public' }
    maven {
        url 'https://maven.google.com'
    }
    maven {
        url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
    }
    maven {
        url 'https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/ec-android-sdk'
    }
    maven {
        url 'https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/'
    }
}

android {
....
....
}

dependencies {
...
implementation 'com.onesignal:OneSignal:3.10.6'
...
}
```

build.gradle file 
```sh
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.21'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1
        classpath 'com.google.gms:google-services:4.2.0'
        classpath "io.realm:realm-gradle-plugin:5.8.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
...
}
```

**Comment by demo-Ashif** [comment] 2019-05-06 12:55
using version 3.10.8 solved my issue.

**Comment by jkasten2** [comment] 2019-05-22 20:28
@SuyashBDA The Google and Firebase libraries should be getting pulled from `https://maven.google.com` however according to the error you are getting Gradle is trying to pull it from `https://s3-ap-southeast-1.amazonaws.com/` instead. I see google is before this aws url in your `repositories { ... }` so this isn't the issue, this is normally the cause of the issue.

Are you getting these errors when running from Android Studio or from running `./gradew` from the terminal? I recommend trying to do a clean build a resync gradle, it is possible something is being cached. Make sure you aren't running Android Studio in offline mode.

I also recommend updating `gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.1` to version `0.12.2` and `com.onesignal:OneSignal:3.10.6` to version `3.10.8`. This won't have an effect on the specific issue you are seeing however these are updates we recommend on getting to prevent other issues.

@demo-Ashif Dependencies haven't changed in any of the 3.10.x versions of this OneSignal SDK, maybe you did a clean build to solve this same issue?

**Comment by jkasten2** [comment] 2019-07-25 23:05
Closing issue as it is now resolved

**Closed by jkasten2** 2019-07-25 23:05 UTC
