### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99]

### ISSUE THREAD

**Issue by JTripathy4** [OneSignal/OneSignal-Gradle-Plugin#121] opened 2020-05-10 20:16 UTC
**Gradle Sync Error**
`ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99]`

**Build.gradle (project)**

   // Top-level build file where you can add configuration options common to all sub-projects/modules.

    buildscript {

        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.6.3'
            classpath 'com.google.gms:google-services:4.3.3'

            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }

    allprojects {
        repositories {
            google()
            mavenLocal()
            jcenter()
            maven { url "https://maven.google.com" }

        }
    }

    task clean(type: Delete) {
        delete rootProject.buildDir
    }

 **Build.gradle (:app)**

    buildscript {
        repositories {
            maven { url 'https://plugins.gradle.org/m2/' }

        }

        dependencies {
            classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'
        }
    }
    apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

    repositories {
        maven { url 'https://maven.google.com' }
    }

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 28
        useLibrary 'org.apache.http.legacy'

        defaultConfig {
            vectorDrawables {
                useSupportLibrary = true
            }
            vectorDrawables.useSupportLibrary = true

            applicationId "com.game.pubg.best.tournaments"

            // TODO: Please update the OneSignal ID below to yours!
            manifestPlaceholders = [onesignal_app_id: '6554b669-a188-4110-8836-b181ff64894b',
                                    // Project number pulled from dashboard, local value is ignored.
                                    onesignal_google_project_number: 'REMOTE']

            minSdkVersion 19
            targetSdkVersion 28
            versionCode 1
            versionName "1"
            multiDexEnabled true
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
            javaCompileOptions {
                annotationProcessorOptions {
                    includeCompileClasspath false
                }
            }
        }
        repositories {
            mavenCentral()
            maven { url 'http://repo1.maven.org/maven2' }
            maven { url "http://jcenter.bintray.com" }
            maven { url "https://www.jitpack.io" }
            maven { url "https://maven.google.com" }
            maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
            maven { url "https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/" }
            jcenter()
        }
        buildTypes {
            release {
                minifyEnabled true
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
    //        debug {
    //            minifyEnabled true
    //            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    //        }
        }
    }

    apply plugin: 'com.google.gms.google-services'

    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        implementation 'com.android.support:support-vector-drawable:28.0.0'

    //    implementation 'ai.devsupport.instamojo:instamojolib:0.1.6'

        androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.2',
                {
                    exclude group: 'com.android.support', module: 'support-annotations'
                }
        )
        implementation 'com.android.support:appcompat-v7:28.0.0'
        implementation 'com.android.support:cardview-v7:28.0.0'
        implementation 'com.android.support:support-v4:28.0.0'
        implementation 'com.android.support:design:28.0.0'

    //    implementation 'com.google.android.gms:play-services-ads:17.0.0'

        implementation 'de.hdodenhof:circleimageview:3.1.0'
        implementation 'com.facebook.shimmer:shimmer:0.5.0'

        implementation 'me.zhanghai.android.materialprogressbar:library:1.6.1'

        implementation 'com.github.bumptech.glide:glide:4.11.0'

        implementation 'com.onesignal:OneSignal:[3.13.0, 3.99.99]'

        implementation('com.paytm:pgplussdk:1.3.3')
                {
            transitive = true
                }

        implementation 'org.jsoup:jsoup:1.13.1'

        implementation 'com.android.support.constraint:constraint-layout:1.1.3'
        testImplementation 'junit:junit:4.13'
        androidTestImplementation 'com.android.support.test:runner:1.0.2'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

        implementation 'com.google.firebase:firebase-core:16.0.1'
        implementation 'com.google.firebase:firebase-database:16.0.1'
        implementation 'com.google.android.gms:play-services-auth:18.0.0'

    }

**Comment by jkasten2** [comment] 2020-05-10 21:37
@JTripathy4 It seems Gradle 5.6.4 (default when using Android Studio 3.6.3) has a bug where if you have any invalid repositories it will fail on the first dependency it tries to resolve. For some unknown reason it only seems to do this on the UnitTest tasks. 

These two lines repositories are not valid as they now requires HTTPS instead of HTTP.
```gradle
maven { url 'http://repo1.maven.org/maven2' }
maven { url "http://jcenter.bintray.com" }
```

Please update them to the following.
```gradle
maven { url 'https://repo1.maven.org/maven2' }
maven { url "https://jcenter.bintray.com" }
```

**Comment by JTripathy4** [comment] 2020-05-10 21:49
> @JTripathy4 It seems Gradle 5.6.4 (default when using Android Studio 3.6.3) has a bug where if you have any invalid repositories it will fail on the first dependency it tries to resolve. For some unknown reason it only seems to do this on the UnitTest tasks.
> 
> These two lines repositories are not valid as they now requires HTTPS instead of HTTP.
> 
> ```groovy-gradle
> maven { url 'http://repo1.maven.org/maven2' }
> maven { url "http://jcenter.bintray.com" }
> ```
> 
> Please update them to the following.
> 
> ```groovy-gradle
> maven { url 'https://repo1.maven.org/maven2' }
> maven { url "https://jcenter.bintray.com" }
> ```
> 
> I tested Gradle 6.0 and it seems to resolve the invalid repository issue, not necessary but I would recommend updating to this as well.

Okk sir. So now what changes I need to do kindly say to me one by one.
I will do it right now.
Because I'm struggling for 2 days due to this error.

**Comment by jkasten2** [comment] 2020-05-10 21:53
@JTripathy4 While debugging I did some clean up so feel free to use these copies for your project.

`build.gradle`
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.7, 0.99.99]'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

`app/build.gradle`
```gradle
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        vectorDrawables {
            useSupportLibrary = true
        }
        applicationId "com.game.pubg.best.tournaments"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        manifestPlaceholders = [onesignal_app_id: '6554b669-a188-4110-8836-b181ff64894b',
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: 'REMOTE']

        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
//        debug {
//            minifyEnabled true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.android.support:support-vector-drawable:28.0.0'

    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'

    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'

    implementation 'me.zhanghai.android.materialprogressbar:library:1.6.1'

    implementation 'com.github.bumptech.glide:glide:4.11.0'

    implementation 'com.onesignal:OneSignal:[3.13.2, 3.99.99]'

    implementation 'com.paytm:pgplussdk:1.3.3'

    implementation 'org.jsoup:jsoup:1.13.1'

    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-database:16.0.1'
    implementation 'com.google.android.gms:play-services-auth:18.0.0'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by jkasten2** [comment] 2020-05-10 22:57
@JTripathy4 Closing this issue as resolved since we confirmed it was fixed after the change noted above, however feel free to reply with your findings. We can reopen if it did not resolve for you.

**Closed by jkasten2** 2020-05-10 22:57 UTC

**Comment by JTripathy4** [comment] 2020-05-11 05:04
Now I'm facing some issues whole I'm trying to build the app.
[Check this](https://github.com/bumptech/glide/issues/4211)
